create table ex41_bbs(
	num number primary key,
	name varchar2(12),
	sub varchar2(30),
	content varchar2(2000),
	nalja date,
	cnt number(6)
);

create sequence ex41_bbs_seq;

insert into ex41_bbs values (ex41_bbs_seq.nextval,'user01','test1','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test2','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test3','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test4','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test5','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user03','test6','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test7','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test8','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test9','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test10','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test11','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test12','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test13','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test14','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user01','test15','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test16','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test17','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test18','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test19','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test20','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test21','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test22','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test23','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test24','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test25','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test26','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test27','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test28','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test29','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test30','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test31','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test32','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test33','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test34','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test35','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test36','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test37','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user01','test38','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test39','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test40','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user03','test41','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test42','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test43','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test44','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test45','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test46','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test47','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test48','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test49','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test50','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test51','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test52','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test53','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test54','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test55','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test56','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test57','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test58','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test59','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test60','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test61','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user01','test62','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test63','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test64','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test65','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user03','test66','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test67','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test68','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test69','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test70','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test71','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test72','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test73','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test74','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test75','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test76','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user01','test77','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test78','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test79','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test80','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user01','test81','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test82','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test83','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test84','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test85','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test86','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test87','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user02','test88','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test89','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test90','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test91','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test92','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test93','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test94','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user01','test95','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test96','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test97','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'user01','test98','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test99','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test100','test',sysdate,0);
insert into ex41_bbs values (ex41_bbs_seq.nextval,'tester','test101','test',sysdate,0);
commit;